### ISSUE TITLE
Fix CI build

### ISSUE THREAD

**Issue by iamareebjamal** [open-roboclub/roboclub-flutter#3]
Build is failing

**Comment by Rishabhltfb** [comment]
This worked in my repo and gives a complete job. I checked logs the build failure is due to some internal error at Github actions.
If it persists during the next PR. I will fix it then.

**Comment by Rishabhltfb** [comment]
Flutter CI got triggered automatically and Completed Successfully.

**Comment by iamareebjamal** [comment]
I triggered it
